version: '2'
services:
    websockets2-app:
        image: websockets2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://websockets2-mysql:3306/websockets2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    websockets2-mysql:
        extends:
            file: mysql.yml
            service: websockets2-mysql
